transfer token
pado-labs/pado-ao-process pull request #7
Opened 2024-05-10 07:43 UTC by xiaojiqing

1. add `Allowance` in Tasks process
2. transfer tokens to data provider and compute nodes

2024-05-11 06:19 UTC, fksyuan requested changes

2024-05-11 06:19 UTC, fksyuan commented on src/base.lua
> +TOKEN_FOR_COMPUTATION = 1
TOKEN_FOR_COMPUTATION name can change to TOKEN_FOR_COMPUTATION_PRICE?

2024-05-11 06:19 UTC, fksyuan commented on src/tasks.lua
> +Handlers.add(
The method must be deleted. The completed tasks should not be deleted.

2024-05-11 06:19 UTC, fksyuan commented on src/tasks.lua
Do need to add a withdraw function? After the user submits the task, can I withdraw the recharged money immediately?

2024-05-11 07:47 UTC, xiaojiqing commented on src/tasks.lua
> +Handlers.add(
good advice

2024-05-11 07:47 UTC, xiaojiqing commented on src/base.lua
> +TOKEN_FOR_COMPUTATION = 1
good advice

2024-05-11 07:48 UTC, xiaojiqing commented on src/tasks.lua
i will add withdraw handler

2024-05-13 01:41 UTC, ujnss commented on js_test/tasks.ts
> +    await testAddWhiteList(address, signer)
Calling this directly will return `Forbitten to operate white list`, should `setNodeRegistryManager` be called first? @xiaojiqing

2024-05-16 02:32 UTC, fksyuan approved these changes

2024-05-16 02:33 UTC, merged